ci: setup quality gate job

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -9,12 +9,46 @@ env:
   imageName: fdpg-pdf
   isMain: ${{ github.ref == 'refs/heads/main' }}
   isDev: ${{ github.ref == 'refs/heads/dev' }}
+  nodeVersion: 16
 
 
 jobs:
+  qualitiy_gate:
+    name: "Qualitiy Gate"
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Setup Node"
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{env.nodeVersion}}
+          cache: yarn
+
+      - name: "Installing Modules"
+        run: yarn install
+
+      - name: "Jest Unit Testing"
+        run: yarn test
+
+      - name: "Publish Test Results"
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/reports/junit.xml'
+          fail_on_failure: true
+
+      - name: "Publish Code Coverage"
+        uses: 5monkeys/cobertura-action@master
+        if: ${{ github.event_name == 'pull_request' }}
+        with:
+          path: reports/coverage/cobertura-coverage.xml
+          minimum_coverage: 75
+          fail_below_threshold: false
+          only_changed_files: true
+
   build_container_image:
     name: "Build Container Image"
     runs-on: ubuntu-latest
+    needs: qualitiy_gate
     steps:
       - uses: actions/checkout@v3
 
